apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # port used inside the cluster
      targetPort: 80  # container port
  type: ClusterIP
